### ISSUE TITLE
Blank page on redis management screen

### ISSUE THREAD

**Issue by dvdmierden** [steverobbins/Magento-Redismanager#13]
Sorry cross-post, the other issue (https://github.com/steverobbins/Magento-Redismanager/issues/6) remained closed. I have the same problem: blank screen on redis management page.
I installed via modman and got this error in the system.log file:

2015-07-30T07:07:18+00:00 CRIT (2): Not valid template file:adminhtml/default/default/template/steverobbins/redismanager/manager.phtml

I looked it up, and it exists. Tried logout/login, clear cache. No luck. Any thoughts?

**Comment by steverobbins** [comment]
This error comes from `app/code/core/Mage/Core/Block/Template.php` around line 238

```
        try {
            $includeFilePath = realpath($this->_viewDir . DS . $fileName);
            if (strpos($includeFilePath, realpath($this->_viewDir)) === 0 || $this->_getAllowSymlinks()) {
                include $includeFilePath;
            } else {
                Mage::log('Not valid template file:'.$fileName, Zend_Log::CRIT, null, null, true);
            }

        } catch (Exception $e) {
            ob_get_clean();
            throw $e;
        }
```

To help debug this issue, could you `var_dump` out some values?  Modify the above to look like

```
        try {
            $includeFilePath = realpath($this->_viewDir . DS . $fileName);
            if (strpos($includeFilePath, realpath($this->_viewDir)) === 0 || $this->_getAllowSymlinks()) {
                include $includeFilePath;
            } else {
                var_dump(
                    'fileName: ' . $fileName,
                    'viewDir: ' . $this->_viewDir,
                    'realpath(viewDir): ' . realpath($this->_viewDir),
                    'includeFilePath: ' . $includeFilePath,
                    'getAllowSymlinks: ' . (int) $this->_getAllowSymlinks()
                );
                exit;
                Mage::log('Not valid template file:'.$fileName, Zend_Log::CRIT, null, null, true);
            }

        } catch (Exception $e) {
            ob_get_clean();
            throw $e;
        }
```

**Comment by Tijmen78** [comment]
Hi Steve, 
Same sort off problem here, magento 1.7.0.2 on 2 installs, it makes the redis management page show menu header and footer but midlle section blank and the system>configuration just complete blank.

system.log says:
2015-08-04T20:54:12+00:00 ERR (3): Deprecated functionality: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated  in /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/Zend_Validate_Hostname.php on line 521
2015-08-04T20:54:12+00:00 ERR (3): Deprecated functionality: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated  in /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/Zend_Validate_Hostname.php on line 617

exception.log says:
exception 'Mage_Core_Exception' with message 'Ongeldig bloktype: Steverobbins_Redismanager_Block_Adminhtml_Manager' in /srv/users/test1toolmaster/apps/test1toolmaster/public/app/Mage.php:594
Stack trace:
#0 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27348): Mage::throwException('Ongeldig blokty...')
#1 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27290): Mage_Core_Model_LayoutOverriddenClass->_getBlockInstance('redismanager/ad...', Array)
#2 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27325): Mage_Core_Model_LayoutOverriddenClass->createBlock('redismanager/ad...', 'redismanager.ma...')
#3 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27092): Mage_Core_Model_LayoutOverriddenClass->addBlock('redismanager/ad...', 'redismanager.ma...')
#4 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27058): Mage_Core_Model_LayoutOverriddenClass->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(27063): Mage_Core_Model_LayoutOverriddenClass->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(13507): Mage_Core_Model_LayoutOverriddenClass->generateBlocks()
#7 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(13432): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/Mage_Adminhtml_Controller_Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#9 /srv/users/test1toolmaster/apps/test1toolmaster/public/app/code/community/Steverobbins/Redismanager/controllers/Adminhtml/RedismanagerController.php(54): Mage_Adminhtml_Controller_Action->loadLayout()
#10 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(13582): Steverobbins_Redismanager_Adminhtml_RedismanagerController->indexAction()
#11 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(17927): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(17484): Mage_Core_Controller_Varien_Router_StandardOverriddenClass->match(Object(Mage_Core_Controller_Request_Http))
#13 /srv/users/test1toolmaster/apps/test1toolmaster/public/includes/src/__default.php(20076): Mage_Core_Controller_Varien_Front->dispatch()
#14 /srv/users/test1toolmaster/apps/test1toolmaster/public/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#15 /srv/users/test1toolmaster/apps/test1toolmaster/public/index.php(64): Mage::run('particulier')
#16 {main}

It would be great if a solution could be found.
Many Thanks, Tijmen

**Comment by steverobbins** [comment]
@Tijmen78 your issue doesn't seem to be related.  Have you recompiled your store?

**Comment by Tijmen78** [comment]
Hi Steve,

 

I don’t use compilation.

Emptied cache, flushed redis multiple times from terminal, logged out and in.

Only option put the module on false helps.

Seems to be something with an block that is not good or allowed, it says ongeldig bloktype witch translates to invalid blocktype. But I am not a code writer so I don’t really understand it.

(The part with Deprecated functionality: iconv_set_encoding(): seems to have another origin, it stays in the log with your module off.)

 

Kind regards,

Tijmen

 

Van: Steve Robbins [mailto:notifications@github.com] 
Verzonden: woensdag 5 augustus 2015 0:13
Aan: steverobbins/Magento-Redismanager
CC: Tijmen78
Onderwerp: Re: [Magento-Redismanager] Blank page on redis management screen (#13)

 

@Tijmen78 <https://github.com/Tijmen78>  your issue doesn't seem to be related. Have you recompiled your store?

**Comment by steverobbins** [comment]
Closing this for now.

@dvdmierden, please comment if you would like to continue debugging.
