### ISSUE TITLE
Databases only show Name: Session Database: 2

### ISSUE THREAD

**Issue by nilands55s** [steverobbins/Magento-Redismanager#22]
Hello Mr Steve Robbins
Should there also be a database for cache for /var/cache/
Also I need help on my local.xml. I have search and still I am not clear about if the /var/cache folder should stay empty if redis is working correctly. There seem to either be conflicting information or a lot of post are confused about this? On mine it I empty the directory it stays empty only for a short while. Some think redis also makes files there as a backup? But if I use APC it would stay empty normally, so would not redis do the same? a pointer would be great!
![redis-manager_2016-02-16 14 38 26](https://cloud.githubusercontent.com/assets/8949704/13194288/d171171a-d759-11e5-8c6e-ecb9052eab44.png)

**Comment by steverobbins** [comment]
`/var/cache` should be empty if Redis is being used for cache storage.  This sounds like a problem unrelated to this extension.  You should try asking this question for help on magento.stackexchange.com.
