### ISSUE TITLE
Redis databases not flushing from admin

### ISSUE THREAD

**Issue by vlmironoff** [steverobbins/Magento-Redismanager#23]
Hello Steve,
First of all thank you for the great module you created. I have noticed a little weird behavior flushing redis databases.
I installed Redis and created 2 databases on the default instance - for cache and for sessions. Redismanager was working perfectly, when i hit flush all it flushed all dbs and since all sessions were gone i was automatically logged out on refresh.
Then I decided to fire up a separate instance of redis and move sessions there: RedisManager picked up this change perfectly, however when I click Flush All (or flush individual db) - the module displays success message but the session is still there - neither i'm being logged out nor session gets evicted when i do KEYS \* in redis-cli.
Please suggest.
Thank you!

**Comment by steverobbins** [comment]
Which flushall button are you using?  Can you share your redis configuration from `local.xml` and/or a screenshot of the Redis Management section in the admin?

**Comment by vlmironoff** [comment]
I tried using each and every button that has the word FLUSH on it: the one to flush all dbs on all instances of redis (button on the very top), the one flushing all dbs on individual  instance, the one flushing individual db.
Here is the redis config from local.xml:

`<cache>
          <backend>Mage_Cache_Backend_Redis</backend>
          <backend_options>
            <server>127.0.0.1</server>
            <port>6379</port>
            <persistent></persistent>
            <database>0</database>
            <password></password>
            <force_standalone>0</force_standalone>
            <connect_retries>1</connect_retries>
            <read_timeout>10</read_timeout>
            <automatic_cleaning_factor>0</automatic_cleaning_factor>
            <compress_data>1</compress_data>
            <compress_tags>1</compress_tags>
            <compress_threshold>20480</compress_threshold>
            <compression_lib>gzip</compression_lib>
          </backend_options>
        </cache>

	<session_save>db</session_save>
        <redis_session>
            <host>127.0.0.1</host>
            <port>6380</port>
            <password></password>
            <timeout>2.5</timeout>
            <persistent></persistent>
            <db>0</db>
            <compression_threshold>2048</compression_threshold>
            <compression_lib>gzip</compression_lib>
            <log_level>1</log_level>
            <max_concurrency>6</max_concurrency>
            <break_after_frontend>5</break_after_frontend>
            <break_after_adminhtml>30</break_after_adminhtml>
            <first_lifetime>600</first_lifetime>
            <bot_first_lifetime>60</bot_first_lifetime>
            <bot_lifetime>7200</bot_lifetime>
            <disable_locking>0</disable_locking>
            <min_lifetime>60</min_lifetime> 
            <max_lifetime>86400</max_lifetime>        
	</redis_session>
`

**Comment by steverobbins** [comment]
It's working as expected for me when testing.  Are you sure Redis is being used for sessions?  Have you enabled the `Cm_RedisSession` module?

Try connecting to the Redis instance

    telnet 127.0.0.1 6380

And watch using the `monitor` command.  Do you see the `flushall`/`flushdb` command go through when hitting the button in the admin?

**Comment by vlmironoff** [comment]
Yes Cm_RedisSession module is enabled. When I connect to redis instance (6380) and do FLUSHALL command - it clears all the data and refreshing the admin panel page in magento shortly after that gets me logged out. However when I click Flush All button in the module - it says: 127.0.0.1:6380 flushed, but when I reload the page again - I'm not logged out, meaning the session is not wiped. I tried enabling MONITOR mode as you suggested and here is the output: 
`127.0.0.1:6380> monitor
OK
//CLICKING Flush ALL Button
1458678076.284583 [0 127.0.0.1:56866] "HINCRBY" "sess_phqh2oqc0g94dvba7v1ufjvk07" "lock" "1"
1458678076.284980 [0 127.0.0.1:56866] "HMSET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "pid" "magento-webstore-development|21495" "lock" "1"
1458678076.284995 [0 127.0.0.1:56866] "EXPIRE" "sess_phqh2oqc0g94dvba7v1ufjvk07" "1440"
1458678076.285146 [0 127.0.0.1:56866] "HGET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "data"
1458678076.300223 [0 127.0.0.1:56868] "SELECT" "0"
1458678076.300401 [0 127.0.0.1:56868] "FLUSHALL"
1458678076.305760 [0 127.0.0.1:56866] "HGET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "pid"
1458678076.307081 [0 127.0.0.1:56866] "SELECT" "0"
1458678076.307166 [0 127.0.0.1:56866] "HMSET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "data" ":gz: [BUNCH OF DATA]" "lock" "0"
1458678076.308966 [0 127.0.0.1:56866] "HINCRBY" "sess_phqh2oqc0g94dvba7v1ufjvk07" "writes" "1"
1458678076.308972 [0 127.0.0.1:56866] "EXPIRE" "sess_phqh2oqc0g94dvba7v1ufjvk07" "1440"
1458678076.734540 [0 127.0.0.1:56870] "HINCRBY" "sess_phqh2oqc0g94dvba7v1ufjvk07" "lock" "1"
1458678076.734797 [0 127.0.0.1:56870] "HMSET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "pid" "magento-webstore-development|21495" "lock" "1"
1458678076.734812 [0 127.0.0.1:56870] "EXPIRE" "sess_phqh2oqc0g94dvba7v1ufjvk07" "1440"
1458678076.734910 [0 127.0.0.1:56870] "HGET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "data"
1458678078.116938 [0 127.0.0.1:56878] "SELECT" "0"
1458678078.117168 [0 127.0.0.1:56878] "INFO"
1458678078.118075 [0 127.0.0.1:56878] "KEYS" "*"
1458678078.121018 [0 127.0.0.1:56880] "SELECT" "0"
1458678078.121213 [0 127.0.0.1:56880] "INFO"
1458678078.122115 [0 127.0.0.1:56880] "KEYS" "*"
1458678078.661337 [0 127.0.0.1:56870] "HGET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "pid"
1458678078.662866 [0 127.0.0.1:56870] "SELECT" "0"
1458678078.662988 [0 127.0.0.1:56870] "HMSET" "sess_phqh2oqc0g94dvba7v1ufjvk07" "data" ":gz: [BUNCH OF DATA]" "lock" "0"
1458678078.664880 [0 127.0.0.1:56870] "HINCRBY" "sess_phqh2oqc0g94dvba7v1ufjvk07" "writes" "1"
1458678078.664888 [0 127.0.0.1:56870] "EXPIRE" "sess_phqh2oqc0g94dvba7v1ufjvk07" "1440"`
