### ISSUE TITLE
1.9.4

### ISSUE THREAD

**Issue by cidrik** [steverobbins/Magento-Redismanager#26]
Hi,
Manager doesn't work with 1.9.4. magento version. Shows empty page.

**Comment by simkea** [comment]
You probably mean Magento CE 1.9.2.4 ?

**Comment by cidrik** [comment]
Yes.

**Comment by cidrik** [comment]
I found the reason, symliks are disabled since 1.9.3.3.
Now modman's installation way  is not acceptable.

**Comment by simkea** [comment]
Add this in your /app/etc/config.xml

```
<default>
...
        <dev>
            <template>
                <allow_symlink>1</allow_symlink>
            </template>
        </dev>
...
</default>
```
and add something like this to a file ... adminhtml/base/default/layout/your.xml

```
<layout>
    <default>
        <reference name="notifications">
            <remove name="notification_symlink"/>
        </reference>
...
</layout>
```
