### ISSUE TITLE
blank page on "redis management" menu

### ISSUE THREAD

**Issue by jacko972** [steverobbins/Magento-Redismanager#6]
Hi,
I've flushed all kind of magento cache but when I go on 
System > Redis Management, the page is blank.
I have not errors logged.
Additionnally, the modules works on my dev environment but not in the producition.

**Comment by dvdmierden** [comment]
Sorry for the kick. I have the same problem: blank screen on redis management page.
I installed via modman and got this error in the system.log file:

`2015-07-30T07:07:18+00:00 CRIT (2): Not valid template file:adminhtml/default/default/template/steverobbins/redismanager/manager.phtml`

I looked it up, and it exists. Tried logout/login, clear cache. No luck. Any thoughts?
